"""INTF-002 Phase 1: supplier catalog layer + reactive requirement sync foundation.

Revision ID: 0023
Revises: 0022
Create Date: 2026-04-30

(Spec §5.1 calls this migration "0008" using its pre-audit numbering — the
actual sequential number after audit Phase 4 is 0023.)

Adds the entire global supplier-catalog layer plus the requirement-sync and
coverage-exception substrates referenced by Phases 2-6 of ASTRA-TDD-INTF-002:

  Suppliers / SupplierDocument / CatalogPart / CatalogConnector / CatalogPin
  PendingCatalogImport
  RequirementSourceLink / RequirementSyncProposal
  CoverageException

Plus column-level extensions to existing tables:

  units:        + catalog_part_id, location_zone, serial_number, asset_tag
  pins:         + catalog_pin_id, mfr_pin_name, internal_signal_name,
                  direction_override, function_override
  requirements: + sync_locked, sync_locked_reason, sync_locked_by_id,
                  sync_locked_at, generation_template_id

Hand-written per spec §5 — not autogenerated.

PG enum naming
--------------
The catalog enums for `ConnectorGender`, `SignalType`, `SignalDirection` use
PG type names `catalog_connector_gender`, `catalog_signal_type`,
`catalog_signal_direction` to avoid collision with the existing `connectorgender`
and `signaltype` enums created by earlier migrations for the project-side
`Pin.signal_type` and `Connector.gender` columns.

Backfill
--------
1. `pins.internal_signal_name = pins.mfr_pin_name = pins.signal_name`
   (spec §5.1 step 14 says `pins.name`, but the existing schema's column is
   `signal_name`. Migration takes signal_name as the seed for the new fields.)
2. `requirement_source_links` from `interface_requirement_links` (1-to-1).
3. `requirements.generation_template_id` from `auto_requirement_logs` join
   where the log's trigger_entity matches a single requirement-link — best-effort.

Reversibility
-------------
The down() block reverses every step in opposite order. Tested up→down→up on
the dev DB after initial apply. No audit_log row mutations performed.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "0023"
down_revision: Union[str, None] = "0022"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── Catalog-side enum value sets (must match app/models/catalog.py exactly) ──
_PART_CLASS = (
    "processor", "sensor", "power_supply", "radio", "antenna", "actuator",
    "display", "harness", "connector_only", "compute_module",
    "power_distribution", "interface_card", "other",
)
_LRU_CLASS = ("lru", "sru", "wra", "subassembly", "component")
_LIFECYCLE_STATUS = (
    "active", "preferred", "obsolete", "eol_announced", "nrnd", "restricted",
)
_CATALOG_CONNECTOR_GENDER = ("male", "female", "hermaphroditic", "unknown")
_CATALOG_SIGNAL_TYPE = (
    "power", "ground", "digital", "analog", "diff_pair", "rf",
    "discrete", "no_connect", "reserved", "unknown",
)
_CATALOG_SIGNAL_DIRECTION = (
    "input", "output", "bidirectional", "power", "ground", "unknown",
)
_SUPPLIER_DOCUMENT_TYPE = (
    "icd", "datasheet", "spec_sheet", "drawing", "app_note", "user_manual", "other",
)
_EXTRACTION_STATUS = (
    "uploaded", "extracting", "pending_review", "approved", "rejected", "failed",
)
_PENDING_IMPORT_STATUS = ("pending", "approved", "rejected", "superseded")
_SOURCE_ENTITY_TYPE = (
    "system", "unit", "connector", "pin", "interface", "wire_harness", "wire",
    "bus_definition", "message_definition", "message_field", "unit_env_spec",
    "catalog_part", "requirement",
)
_SYNC_PROPOSAL_TYPE = ("update_statement", "obsolete", "regenerate")
_SYNC_PROPOSAL_STATUS = (
    "pending", "accepted", "rejected", "auto_applied", "superseded",
)


def _create_enum(name: str, values: tuple[str, ...]) -> postgresql.ENUM:
    """Create a PG ENUM type and return the type object for column reuse."""
    enum_t = postgresql.ENUM(*values, name=name, create_type=False)
    enum_t.create(op.get_bind(), checkfirst=True)
    return enum_t


def upgrade() -> None:
    # ──────────────────────────────────────────────────────────
    # Step 1: enum types (PG forbids forward references)
    # ──────────────────────────────────────────────────────────
    part_class_t        = _create_enum("part_class", _PART_CLASS)
    lru_class_t         = _create_enum("lru_class", _LRU_CLASS)
    lifecycle_status_t  = _create_enum("lifecycle_status", _LIFECYCLE_STATUS)
    cat_gender_t        = _create_enum("catalog_connector_gender", _CATALOG_CONNECTOR_GENDER)
    cat_signal_t        = _create_enum("catalog_signal_type", _CATALOG_SIGNAL_TYPE)
    cat_direction_t     = _create_enum("catalog_signal_direction", _CATALOG_SIGNAL_DIRECTION)
    supplier_doctype_t  = _create_enum("supplier_document_type", _SUPPLIER_DOCUMENT_TYPE)
    extraction_status_t = _create_enum("extraction_status", _EXTRACTION_STATUS)
    pending_status_t    = _create_enum("pending_import_status", _PENDING_IMPORT_STATUS)
    source_entity_t     = _create_enum("source_entity_type", _SOURCE_ENTITY_TYPE)
    sync_proposal_t     = _create_enum("sync_proposal_type", _SYNC_PROPOSAL_TYPE)
    sync_status_t       = _create_enum("sync_proposal_status", _SYNC_PROPOSAL_STATUS)

    # ──────────────────────────────────────────────────────────
    # Step 2: suppliers
    # ──────────────────────────────────────────────────────────
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("short_name", sa.String(50), nullable=True),
        sa.Column("cage_code", sa.String(10), nullable=True),
        sa.Column("duns", sa.String(15), nullable=True),
        sa.Column("website", sa.String(500), nullable=True),
        sa.Column("address", sa.Text, nullable=True),
        sa.Column("country", sa.String(100), nullable=True),
        sa.Column("primary_contact", sa.String(200), nullable=True),
        sa.Column("primary_email", sa.String(200), nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("is_active", sa.Boolean, server_default=sa.text("TRUE"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")),
        sa.Column("created_by_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        sa.UniqueConstraint("name", name="uq_suppliers_name"),
    )
    op.create_index("ix_suppliers_name", "suppliers", ["name"])
    op.create_index("ix_suppliers_cage_code", "suppliers", ["cage_code"])

    # ──────────────────────────────────────────────────────────
    # Step 3: supplier_documents
    # ──────────────────────────────────────────────────────────
    op.create_table(
        "supplier_documents",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "supplier_id", sa.Integer,
            sa.ForeignKey("suppliers.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("document_type", supplier_doctype_t, nullable=False),
        sa.Column("revision", sa.String(50), nullable=True),
        sa.Column("document_number", sa.String(200), nullable=True),
        sa.Column("publication_date", sa.Date, nullable=True),
        sa.Column("file_path", sa.String(1000), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger, nullable=False),
        sa.Column("sha256", sa.String(64), nullable=False),
        sa.Column("mime_type", sa.String(100), nullable=False),
        sa.Column("page_count", sa.Integer, nullable=True),
        sa.Column(
            "extraction_status", extraction_status_t, nullable=False,
            server_default=sa.text("'uploaded'::extraction_status"),
        ),
        sa.Column("extraction_log", postgresql.JSONB, nullable=True),
        sa.Column("extraction_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")),
        sa.Column("uploaded_by_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
    )
    op.create_index("ix_supplier_documents_supplier_id", "supplier_documents", ["supplier_id"])
    op.create_index("ix_supplier_documents_sha256", "supplier_documents", ["sha256"])

    # ──────────────────────────────────────────────────────────
    # Step 4: catalog_parts (defer self-FK on parent_part_id)
    # ──────────────────────────────────────────────────────────
    op.create_table(
        "catalog_parts",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("supplier_id", sa.Integer, sa.ForeignKey("suppliers.id"), nullable=False),
        sa.Column("part_number", sa.String(200), nullable=False),
        sa.Column("revision", sa.String(50), nullable=True),
        sa.Column("name", sa.String(500), nullable=False),
        sa.Column("designation", sa.String(200), nullable=True),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("part_class", part_class_t, nullable=False),
        sa.Column(
            "lru_classification", lru_class_t, nullable=False,
            server_default=sa.text("'lru'::lru_class"),
        ),
        sa.Column("mass_kg", sa.Numeric(10, 4), nullable=True),
        sa.Column("dim_length_mm", sa.Numeric(10, 2), nullable=True),
        sa.Column("dim_width_mm", sa.Numeric(10, 2), nullable=True),
        sa.Column("dim_height_mm", sa.Numeric(10, 2), nullable=True),
        sa.Column("power_watts_nominal", sa.Numeric(10, 3), nullable=True),
        sa.Column("power_watts_peak", sa.Numeric(10, 3), nullable=True),
        sa.Column("voltage_input_min_v", sa.Numeric(10, 2), nullable=True),
        sa.Column("voltage_input_max_v", sa.Numeric(10, 2), nullable=True),
        sa.Column("temp_operating_min_c", sa.Numeric(6, 2), nullable=True),
        sa.Column("temp_operating_max_c", sa.Numeric(6, 2), nullable=True),
        sa.Column("temp_storage_min_c", sa.Numeric(6, 2), nullable=True),
        sa.Column("temp_storage_max_c", sa.Numeric(6, 2), nullable=True),
        sa.Column("vibration_random_grms", sa.Numeric(8, 3), nullable=True),
        sa.Column("shock_mechanical_g", sa.Numeric(8, 2), nullable=True),
        sa.Column("humidity_max_pct", sa.Numeric(5, 2), nullable=True),
        sa.Column("altitude_max_m", sa.Numeric(10, 2), nullable=True),
        sa.Column("emi_ce102_limit_dbua", sa.Numeric(8, 2), nullable=True),
        sa.Column("emi_rs103_limit_vm", sa.Numeric(8, 2), nullable=True),
        sa.Column("esd_hbm_v", sa.Numeric(10, 2), nullable=True),
        sa.Column("mil_std_810_tested", sa.Boolean, server_default=sa.text("FALSE")),
        sa.Column("mil_std_461_tested", sa.Boolean, server_default=sa.text("FALSE")),
        sa.Column("rohs_compliant", sa.Boolean, server_default=sa.text("FALSE")),
        sa.Column("itar_controlled", sa.Boolean, server_default=sa.text("FALSE")),
        sa.Column("export_classification", sa.String(50), nullable=True),
        sa.Column(
            "lifecycle_status", lifecycle_status_t, nullable=False,
            server_default=sa.text("'active'::lifecycle_status"),
        ),
        sa.Column("eol_date", sa.Date, nullable=True),
        # Self-FK is added after table creation to avoid forward-reference issues
        sa.Column("parent_part_id", sa.Integer, nullable=True),
        sa.Column("variant_label", sa.String(100), nullable=True),
        sa.Column(
            "source_document_id", sa.Integer,
            sa.ForeignKey("supplier_documents.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("source_page_refs", postgresql.JSONB, nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("image_path", sa.String(1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")),
        sa.Column("created_by_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        sa.UniqueConstraint(
            "supplier_id", "part_number", "revision", name="uq_catalog_part_pn_rev"
        ),
    )
    op.create_index("ix_catalog_parts_supplier_id", "catalog_parts", ["supplier_id"])
    op.create_index("ix_catalog_parts_part_number", "catalog_parts", ["part_number"])
    op.create_index("ix_catalog_parts_parent_part_id", "catalog_parts", ["parent_part_id"])
    op.create_index("ix_catalog_part_search", "catalog_parts", ["part_number", "name"])
    op.create_index(
        "ix_catalog_part_class_status", "catalog_parts",
        ["part_class", "lifecycle_status"],
    )
    # Now the deferred self-FK
    op.create_foreign_key(
        "fk_catalog_parts_parent_part",
        "catalog_parts", "catalog_parts",
        ["parent_part_id"], ["id"],
        ondelete="SET NULL",
    )

    # ──────────────────────────────────────────────────────────
    # Step 5: catalog_connectors
    # ──────────────────────────────────────────────────────────
    op.create_table(
        "catalog_connectors",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "catalog_part_id", sa.Integer,
            sa.ForeignKey("catalog_parts.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("reference", sa.String(50), nullable=False),
        sa.Column("position", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("description", sa.String(500), nullable=True),
        sa.Column("connector_type", sa.String(100), nullable=True),
        sa.Column("shell_size", sa.String(50), nullable=True),
        sa.Column("insert_arrangement", sa.String(50), nullable=True),
        sa.Column("gender", cat_gender_t, nullable=True),
        sa.Column("pin_count", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("keying", sa.String(50), nullable=True),
        sa.Column("mating_part_number", sa.String(200), nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.UniqueConstraint(
            "catalog_part_id", "reference", name="uq_catalog_connector_ref"
        ),
    )
    op.create_index("ix_catalog_connector_part", "catalog_connectors", ["catalog_part_id"])

    # ──────────────────────────────────────────────────────────
    # Step 6: catalog_pins
    # ──────────────────────────────────────────────────────────
    op.create_table(
        "catalog_pins",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "catalog_connector_id", sa.Integer,
            sa.ForeignKey("catalog_connectors.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("pin_position", sa.String(20), nullable=False),
        sa.Column("mfr_pin_name", sa.String(100), nullable=False),
        sa.Column("mfr_signal_function", sa.String(500), nullable=True),
        sa.Column("mfr_signal_type", cat_signal_t, nullable=True),
        sa.Column(
            "mfr_direction", cat_direction_t, nullable=True,
            server_default=sa.text("'unknown'::catalog_signal_direction"),
        ),
        sa.Column("mfr_voltage_min_v", sa.Numeric(8, 3), nullable=True),
        sa.Column("mfr_voltage_max_v", sa.Numeric(8, 3), nullable=True),
        sa.Column("mfr_current_max_ma", sa.Numeric(10, 3), nullable=True),
        sa.Column("mfr_impedance_ohm", sa.Numeric(10, 2), nullable=True),
        sa.Column("mfr_protocol_hint", sa.String(100), nullable=True),
        sa.Column("mfr_is_paired_with", sa.String(50), nullable=True),
        sa.Column("is_no_connect", sa.Boolean, server_default=sa.text("FALSE")),
        sa.Column("is_reserved", sa.Boolean, server_default=sa.text("FALSE")),
        sa.Column("is_chassis_ground", sa.Boolean, server_default=sa.text("FALSE")),
        sa.Column("notes", sa.Text, nullable=True),
        sa.UniqueConstraint(
            "catalog_connector_id", "pin_position", name="uq_catalog_pin_position"
        ),
    )
    op.create_index("ix_catalog_pin_connector", "catalog_pins", ["catalog_connector_id"])

    # ──────────────────────────────────────────────────────────
    # Step 7: pending_catalog_imports
    # ──────────────────────────────────────────────────────────
    op.create_table(
        "pending_catalog_imports",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "source_document_id", sa.Integer,
            sa.ForeignKey("supplier_documents.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("supplier_id", sa.Integer, sa.ForeignKey("suppliers.id"), nullable=False),
        sa.Column("extracted_data", postgresql.JSONB, nullable=False),
        sa.Column("extraction_warnings", postgresql.JSONB, nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(4, 3), nullable=True),
        sa.Column(
            "status", pending_status_t, nullable=False,
            server_default=sa.text("'pending'::pending_import_status"),
        ),
        sa.Column(
            "committed_catalog_part_id", sa.Integer,
            sa.ForeignKey("catalog_parts.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column("rejection_reason", sa.Text, nullable=True),
        sa.Column("reviewer_notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True),
    )
    op.create_index(
        "ix_pending_imports_source_document_id",
        "pending_catalog_imports", ["source_document_id"],
    )
    # JSONB GIN index per spec §8.2
    op.execute(
        "CREATE INDEX ix_pending_imports_extracted_gin "
        "ON pending_catalog_imports USING gin (extracted_data jsonb_path_ops)"
    )

    # ──────────────────────────────────────────────────────────
    # Step 8: requirement_source_links
    # ──────────────────────────────────────────────────────────
    op.create_table(
        "requirement_source_links",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "requirement_id", sa.Integer,
            sa.ForeignKey("requirements.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("source_entity_type", source_entity_t, nullable=False),
        sa.Column("source_entity_id", sa.Integer, nullable=False),
        sa.Column("template_id", sa.String(100), nullable=False),
        sa.Column("template_inputs", postgresql.JSONB, nullable=False),
        sa.Column(
            "role", sa.String(50), nullable=False,
            server_default=sa.text("'primary'"),
        ),
        sa.Column(
            "last_synced_at", sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
        ),
        sa.UniqueConstraint(
            "requirement_id", "source_entity_type", "source_entity_id",
            name="uq_req_source_unique",
        ),
    )
    op.create_index(
        "ix_req_source_link_entity", "requirement_source_links",
        ["source_entity_type", "source_entity_id"],
    )
    op.create_index(
        "ix_req_source_link_req", "requirement_source_links", ["requirement_id"],
    )
    # JSONB GIN index per spec §8.2
    op.execute(
        "CREATE INDEX ix_req_source_link_inputs_gin "
        "ON requirement_source_links USING gin (template_inputs jsonb_path_ops)"
    )

    # ──────────────────────────────────────────────────────────
    # Step 9: requirement_sync_proposals
    # ──────────────────────────────────────────────────────────
    op.create_table(
        "requirement_sync_proposals",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "requirement_id", sa.Integer,
            sa.ForeignKey("requirements.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("triggered_by_entity_type", source_entity_t, nullable=False),
        sa.Column("triggered_by_entity_id", sa.Integer, nullable=False),
        sa.Column("trigger_event", sa.String(50), nullable=False),
        sa.Column("old_statement", sa.Text, nullable=False),
        sa.Column("new_statement", sa.Text, nullable=True),
        sa.Column("old_rationale", sa.Text, nullable=True),
        sa.Column("new_rationale", sa.Text, nullable=True),
        sa.Column("field_diffs", postgresql.JSONB, nullable=False),
        sa.Column("proposal_type", sync_proposal_t, nullable=False),
        sa.Column(
            "status", sync_status_t, nullable=False,
            server_default=sa.text("'pending'::sync_proposal_status"),
        ),
        sa.Column("auto_applied", sa.Boolean, server_default=sa.text("FALSE")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True),
        sa.Column("reviewer_notes", sa.Text, nullable=True),
    )
    op.create_index(
        "ix_req_sync_proposal_status", "requirement_sync_proposals", ["status"]
    )
    op.create_index(
        "ix_req_sync_proposal_req", "requirement_sync_proposals", ["requirement_id"]
    )

    # ──────────────────────────────────────────────────────────
    # Step 10: coverage_exceptions (per spec §13.6)
    # ──────────────────────────────────────────────────────────
    op.create_table(
        "coverage_exceptions",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "project_id", sa.Integer,
            sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "requirement_id", sa.Integer,
            sa.ForeignKey("requirements.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("reason", sa.Text, nullable=False),
        sa.Column(
            "is_active", sa.Boolean, nullable=False, server_default=sa.text("TRUE"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")),
        sa.Column("created_by_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("approved_by_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint(
            "project_id", "requirement_id", name="uq_coverage_exception_req"
        ),
    )
    op.create_index("ix_coverage_exception_project", "coverage_exceptions", ["project_id"])
    op.create_index("ix_coverage_exception_req", "coverage_exceptions", ["requirement_id"])

    # ──────────────────────────────────────────────────────────
    # Step 11: ALTER TABLE units — catalog linkage + project-instance fields
    # ──────────────────────────────────────────────────────────
    op.add_column(
        "units",
        sa.Column(
            "catalog_part_id", sa.Integer,
            sa.ForeignKey("catalog_parts.id", ondelete="SET NULL"), nullable=True,
        ),
    )
    op.add_column("units", sa.Column("location_zone", sa.String(100), nullable=True))
    op.add_column("units", sa.Column("serial_number", sa.String(200), nullable=True))
    op.add_column("units", sa.Column("asset_tag", sa.String(200), nullable=True))
    op.create_index("ix_units_catalog_part_id", "units", ["catalog_part_id"])

    # ──────────────────────────────────────────────────────────
    # Step 12: ALTER TABLE pins — catalog linkage + dual naming + direction
    # ──────────────────────────────────────────────────────────
    op.add_column(
        "pins",
        sa.Column(
            "catalog_pin_id", sa.Integer,
            sa.ForeignKey("catalog_pins.id", ondelete="SET NULL"), nullable=True,
        ),
    )
    op.add_column("pins", sa.Column("mfr_pin_name", sa.String(100), nullable=True))
    op.add_column(
        "pins",
        sa.Column("internal_signal_name", sa.String(100), nullable=True),
    )
    op.add_column(
        "pins",
        sa.Column("direction_override", cat_direction_t, nullable=True),
    )
    op.add_column("pins", sa.Column("function_override", sa.String(500), nullable=True))
    op.create_index("ix_pins_catalog_pin_id", "pins", ["catalog_pin_id"])
    op.create_index("ix_pins_internal_signal_name", "pins", ["internal_signal_name"])

    # ──────────────────────────────────────────────────────────
    # Step 13: ALTER TABLE requirements — sync controls + template id
    # ──────────────────────────────────────────────────────────
    op.add_column(
        "requirements",
        sa.Column(
            "sync_locked", sa.Boolean, nullable=False,
            server_default=sa.text("FALSE"),
        ),
    )
    op.add_column(
        "requirements", sa.Column("sync_locked_reason", sa.String(500), nullable=True),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "sync_locked_by_id", sa.Integer,
            sa.ForeignKey("users.id"), nullable=True,
        ),
    )
    op.add_column(
        "requirements",
        sa.Column("sync_locked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "requirements",
        sa.Column("generation_template_id", sa.String(100), nullable=True),
    )
    op.create_index(
        "ix_requirements_generation_template_id", "requirements",
        ["generation_template_id"],
    )

    # ──────────────────────────────────────────────────────────
    # Step 14: backfill pins.mfr_pin_name + internal_signal_name
    # Spec §5.1 step 14 says "from pins.name" but the existing schema's
    # column is `signal_name`. The intent is the same: seed the new fields
    # from the only pre-existing user-meaningful name on the row.
    # ──────────────────────────────────────────────────────────
    op.execute(
        "UPDATE pins SET mfr_pin_name = signal_name, "
        "internal_signal_name = signal_name "
        "WHERE signal_name IS NOT NULL AND signal_name <> ''"
    )

    # ──────────────────────────────────────────────────────────
    # Step 15: backfill requirement_source_links from
    # interface_requirement_links (1-to-1).
    #
    # Map old `entity_type` (interfaceentitytype) → new `source_entity_type`
    # (source_entity_type). Some old values have no exact analog (e.g.
    # PIN_BUS_ASSIGNMENT, CABLE_ASSEMBLY, INTERFACE_DOCUMENT) — those rows
    # are skipped (logged below as anomalies in the dev DB if they exist).
    # ──────────────────────────────────────────────────────────
    op.execute(
        """
        INSERT INTO requirement_source_links
            (requirement_id, source_entity_type, source_entity_id,
             template_id, template_inputs, role, last_synced_at)
        SELECT
            irl.requirement_id,
            (CASE irl.entity_type::text
                WHEN 'system'             THEN 'system'
                WHEN 'unit'               THEN 'unit'
                WHEN 'connector'          THEN 'connector'
                WHEN 'pin'                THEN 'pin'
                WHEN 'bus_definition'     THEN 'bus_definition'
                WHEN 'message_definition' THEN 'message_definition'
                WHEN 'message_field'      THEN 'message_field'
                WHEN 'wire_harness'       THEN 'wire_harness'
                WHEN 'wire'               THEN 'wire'
                WHEN 'interface'          THEN 'interface'
            END)::source_entity_type,
            irl.entity_id,
            COALESCE(irl.auto_req_template, 'legacy_migrated'),
            '{}'::jsonb,
            'primary',
            COALESCE(irl.created_at, NOW())
        FROM interface_requirement_links irl
        WHERE irl.entity_type::text IN (
            'system','unit','connector','pin','bus_definition',
            'message_definition','message_field','wire_harness','wire','interface'
        )
        ON CONFLICT (requirement_id, source_entity_type, source_entity_id) DO NOTHING
        """
    )

    # ──────────────────────────────────────────────────────────
    # Step 16: backfill requirements.generation_template_id from
    # auto_requirement_logs where there's a clean 1-to-1 mapping. The old
    # logs table doesn't carry per-requirement template context, but
    # interface_requirement_links does — copy from there when present.
    # ──────────────────────────────────────────────────────────
    op.execute(
        """
        UPDATE requirements r
           SET generation_template_id = sub.template
          FROM (
              SELECT requirement_id, MIN(auto_req_template) AS template
                FROM interface_requirement_links
               WHERE auto_req_template IS NOT NULL
               GROUP BY requirement_id
          ) sub
         WHERE sub.requirement_id = r.id
           AND r.generation_template_id IS NULL
        """
    )


def downgrade() -> None:
    # Reverse-order teardown.

    # 13: requirements column drops + index
    op.drop_index("ix_requirements_generation_template_id", table_name="requirements")
    op.drop_column("requirements", "generation_template_id")
    op.drop_column("requirements", "sync_locked_at")
    op.drop_column("requirements", "sync_locked_by_id")
    op.drop_column("requirements", "sync_locked_reason")
    op.drop_column("requirements", "sync_locked")

    # 12: pins column drops + indexes
    op.drop_index("ix_pins_internal_signal_name", table_name="pins")
    op.drop_index("ix_pins_catalog_pin_id", table_name="pins")
    op.drop_column("pins", "function_override")
    op.drop_column("pins", "direction_override")
    op.drop_column("pins", "internal_signal_name")
    op.drop_column("pins", "mfr_pin_name")
    op.drop_column("pins", "catalog_pin_id")

    # 11: units column drops + index
    op.drop_index("ix_units_catalog_part_id", table_name="units")
    op.drop_column("units", "asset_tag")
    op.drop_column("units", "serial_number")
    op.drop_column("units", "location_zone")
    op.drop_column("units", "catalog_part_id")

    # 10: coverage_exceptions
    op.drop_index("ix_coverage_exception_req", table_name="coverage_exceptions")
    op.drop_index("ix_coverage_exception_project", table_name="coverage_exceptions")
    op.drop_table("coverage_exceptions")

    # 9: requirement_sync_proposals
    op.drop_index("ix_req_sync_proposal_req", table_name="requirement_sync_proposals")
    op.drop_index("ix_req_sync_proposal_status", table_name="requirement_sync_proposals")
    op.drop_table("requirement_sync_proposals")

    # 8: requirement_source_links
    op.execute("DROP INDEX IF EXISTS ix_req_source_link_inputs_gin")
    op.drop_index("ix_req_source_link_req", table_name="requirement_source_links")
    op.drop_index(
        "ix_req_source_link_entity", table_name="requirement_source_links"
    )
    op.drop_table("requirement_source_links")

    # 7: pending_catalog_imports
    op.execute("DROP INDEX IF EXISTS ix_pending_imports_extracted_gin")
    op.drop_index(
        "ix_pending_imports_source_document_id",
        table_name="pending_catalog_imports",
    )
    op.drop_table("pending_catalog_imports")

    # 6: catalog_pins
    op.drop_index("ix_catalog_pin_connector", table_name="catalog_pins")
    op.drop_table("catalog_pins")

    # 5: catalog_connectors
    op.drop_index("ix_catalog_connector_part", table_name="catalog_connectors")
    op.drop_table("catalog_connectors")

    # 4: catalog_parts (drop self-FK first, then table)
    op.drop_constraint(
        "fk_catalog_parts_parent_part", "catalog_parts", type_="foreignkey"
    )
    op.drop_index("ix_catalog_part_class_status", table_name="catalog_parts")
    op.drop_index("ix_catalog_part_search", table_name="catalog_parts")
    op.drop_index("ix_catalog_parts_parent_part_id", table_name="catalog_parts")
    op.drop_index("ix_catalog_parts_part_number", table_name="catalog_parts")
    op.drop_index("ix_catalog_parts_supplier_id", table_name="catalog_parts")
    op.drop_table("catalog_parts")

    # 3: supplier_documents
    op.drop_index("ix_supplier_documents_sha256", table_name="supplier_documents")
    op.drop_index(
        "ix_supplier_documents_supplier_id", table_name="supplier_documents"
    )
    op.drop_table("supplier_documents")

    # 2: suppliers
    op.drop_index("ix_suppliers_cage_code", table_name="suppliers")
    op.drop_index("ix_suppliers_name", table_name="suppliers")
    op.drop_table("suppliers")

    # 1: enum types (after every column referencing them is gone)
    bind = op.get_bind()
    for name in (
        "sync_proposal_status",
        "sync_proposal_type",
        "source_entity_type",
        "pending_import_status",
        "extraction_status",
        "supplier_document_type",
        "catalog_signal_direction",
        "catalog_signal_type",
        "catalog_connector_gender",
        "lifecycle_status",
        "lru_class",
        "part_class",
    ):
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)
