"""
ASTRA — AI Writing Assistant Schemas
========================================
File: backend/app/schemas/ai_writer.py   ← NEW
Path: C:\\Users\\Mason\\Documents\\ASTRA\\backend\\app\\schemas\\ai_writer.py

Pydantic models for the requirement writing assistant:
  - Prose → requirements conversion
  - Requirement improvement / rewrite
  - Requirement decomposition
  - Verification criteria generation
  - Rationale generation
  - Change summary for review boards
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


# ══════════════════════════════════════
#  Generated Requirement (shared output)
# ══════════════════════════════════════

class GeneratedRequirement(BaseModel):
    """A single requirement extracted or generated by AI."""
    title: str = ""
    statement: str = ""
    rationale: str = ""
    req_type: str = "functional"
    priority: str = "medium"
    level: str = "L1"
    confidence: float = Field(0.0, ge=0.0, le=1.0)
    source_fragment: str = ""        # Original prose snippet this came from
    notes: str = ""                  # AI explanation of why this was extracted


# ══════════════════════════════════════
#  Prose → Requirements Conversion
# ══════════════════════════════════════

class ProseConvertRequest(BaseModel):
    prose: str = Field(..., min_length=10, max_length=20000)
    project_context: str = ""        # Project description / domain for better extraction
    target_level: str = "L1"         # Default level for extracted requirements
    domain_hint: str = ""            # e.g., "aerospace", "medical device", "automotive"

class ProseConvertResponse(BaseModel):
    requirements: List[GeneratedRequirement] = []
    total_extracted: int = 0
    source_type: str = ""            # "meeting_notes", "email", "specification", "general"
    ai_available: bool = True
    model_used: str = ""
    warnings: List[str] = []         # e.g., "Some statements were too vague to extract"


# ══════════════════════════════════════
#  Requirement Improvement
# ══════════════════════════════════════

class RewriteSuggestion(BaseModel):
    """A single rewrite suggestion for an existing requirement."""
    rewritten_statement: str = ""
    changes_made: List[str] = []     # ["Removed ambiguous term 'adequate'", "Added measurable threshold"]
    quality_delta: str = ""          # e.g., "+15 estimated quality score"
    explanation: str = ""

class ImproveRequest(BaseModel):
    statement: str = Field(..., min_length=5)
    title: str = ""
    rationale: str = ""
    issues: List[str] = []           # Quality issues from the checker
    domain_context: str = ""

class ImproveResponse(BaseModel):
    original_statement: str = ""
    suggestions: List[RewriteSuggestion] = []
    ai_available: bool = True
    model_used: str = ""


# ══════════════════════════════════════
#  Requirement Decomposition
# ══════════════════════════════════════

class DecomposeRequest(BaseModel):
    statement: str = Field(..., min_length=5)
    title: str = ""
    current_level: str = "L1"
    target_level: str = ""           # Auto-detect if empty (L1→L2, L2→L3, etc.)
    req_type: str = "functional"
    project_context: str = ""

class DecomposeResponse(BaseModel):
    parent_statement: str = ""
    parent_level: str = "L1"
    target_level: str = "L2"
    sub_requirements: List[GeneratedRequirement] = []
    decomposition_rationale: str = ""   # Why this decomposition was chosen
    ai_available: bool = True
    model_used: str = ""


# ══════════════════════════════════════
#  Verification Criteria Generation
# ══════════════════════════════════════

class VerificationStep(BaseModel):
    step_number: int = 0
    action: str = ""
    expected_result: str = ""
    pass_criteria: str = ""

class VerificationCriteria(BaseModel):
    requirement_statement: str = ""
    method: str = "test"             # test, analysis, inspection, demonstration
    method_justification: str = ""
    preconditions: List[str] = []
    steps: List[VerificationStep] = []
    pass_fail_criteria: str = ""
    data_to_record: List[str] = []
    estimated_duration: str = ""
    required_resources: List[str] = []
    ai_available: bool = True
    model_used: str = ""

class GenerateVerificationRequest(BaseModel):
    statement: str = Field(..., min_length=5)
    title: str = ""
    method: str = "test"             # test, analysis, inspection, demonstration
    domain_context: str = ""


# ══════════════════════════════════════
#  Rationale Generation
# ══════════════════════════════════════

class GenerateRationaleRequest(BaseModel):
    statement: str = Field(..., min_length=5)
    title: str = ""
    req_type: str = "functional"
    project_context: str = ""

class GenerateRationaleResponse(BaseModel):
    rationale: str = ""
    alternatives_considered: List[str] = []
    ai_available: bool = True
    model_used: str = ""


# ══════════════════════════════════════
#  Change Summary for Review Board
# ══════════════════════════════════════

class SummarizeChangesRequest(BaseModel):
    changes: List[Dict[str, Any]] = []    # List of {req_id, field, old_value, new_value}
    project_name: str = ""
    board_type: str = "CCB"               # CCB, PRR, CDR, etc.

class SummarizeChangesResponse(BaseModel):
    summary: str = ""
    key_impacts: List[str] = []
    recommendation: str = ""
    ai_available: bool = True
    model_used: str = ""
